name: Check PDF Accessibility (veraPDF)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  accessibility_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run veraPDF Accessibility Check
        run: |
          # 1. Pull the official image
          docker pull verapdf/cli:latest
          
          # 2. Run the container
          docker run --rm -v "${PWD}:/app" -w /app verapdf/cli:latest \
          --flavour ua2 \
          --format json \
          main.pdf > a11y-report.json || true

           docker run --rm -v "${PWD}:/app" -w /app verapdf/cli:latest \
          --flavour ua2 \
          --format text \
          main.pdf > a11y-statement.txt || true
      - name: Write Build Status
        run: |
          TIMESTAMP=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')
          echo "{\"lastBuild\": \"${TIMESTAMP}\"}" > ./build-info/a11y-build-info.json
      - name: Commit and Push Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Add the report
          git add a11y-report.json
          git add a11y-statement.txt
          git add ./build-info/a11y-build-info.json
          git commit -m "Chore: Update PDF accessibility report"
          git push
